import SwiftUI
import MapKit
import CoreLocation

public struct CaminoDestination: Identifiable {
    public let id = UUID()
    public let day: Int
    public let date: Date
    public let locationName: String
    public let hotelName: String
    public let coordinate: CLLocationCoordinate2D
    public let elevationProfile: [(distance: Double, elevation: Double)]
    public let dailyDistance: Double
    public let cumulativeDistance: Double
    
    private static let dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter
    }()
    
    public static var totalDistance: Double {
        allDestinations.last?.cumulativeDistance ?? 0.0
    }
    
    public static let allDestinations: [CaminoDestination] = [
        CaminoDestination(day: 1, date: Self.dateFormatter.date(from: "2024-05-01")!, locationName: "Saint-Jean-Pied-de-Port", hotelName: "Villa Goxoki", 
            coordinate: CLLocationCoordinate2D(latitude: 43.1636, longitude: -1.2386),
            dailyDistance: 0.0,
            cumulativeDistance: 0.0,
            elevationProfile: []),
        CaminoDestination(day: 2, date: Self.dateFormatter.date(from: "2024-05-02")!, locationName: "Roncesvalles", hotelName: "Hotel Roncesvalles", 
            coordinate: CLLocationCoordinate2D(latitude: 43.1472, longitude: -1.2239),
            dailyDistance: 23.9,
            cumulativeDistance: 23.9,
            elevationProfile: [
                (0.0, 200),
                (1.0, 400),
                (2.0, 600),
                (3.0, 800),
                (4.0, 950),
                (5.0, 1000),
                (6.0, 1150),
                (7.0, 1200),
                (8.0, 1450)
            ]),
        CaminoDestination(day: 3, date: Self.dateFormatter.date(from: "2024-05-03")!, locationName: "Zubiri", hotelName: "Hosteria de Zubiri", 
            coordinate: CLLocationCoordinate2D(latitude: 42.9321, longitude: -1.5036),
            dailyDistance: 21.5,
            cumulativeDistance: 45.4,
            elevationProfile: []),
        CaminoDestination(day: 4, date: Self.dateFormatter.date(from: "2024-05-04")!, locationName: "Pamplona", hotelName: "Hotel A Pamplona", 
            coordinate: CLLocationCoordinate2D(latitude: 42.8110, longitude: -1.6450),
            dailyDistance: 21.8,
            cumulativeDistance: 67.2,
            elevationProfile: []),
        CaminoDestination(day: 5, date: Self.dateFormatter.date(from: "2024-05-05")!, locationName: "Puente la Reina", hotelName: "Hotel El Cerco", 
            coordinate: CLLocationCoordinate2D(latitude: 42.6728, longitude: -1.8115),
            dailyDistance: 24.2,
            cumulativeDistance: 91.4,
            elevationProfile: []),
        CaminoDestination(day: 6, date: Self.dateFormatter.date(from: "2024-05-06")!, locationName: "Estella", hotelName: "Alda Estella Hostal", 
            coordinate: CLLocationCoordinate2D(latitude: 42.6708, longitude: -2.0295),
            dailyDistance: 21.6,
            cumulativeDistance: 113.0,
            elevationProfile: []),
        CaminoDestination(day: 7, date: Self.dateFormatter.date(from: "2024-05-07")!, locationName: "Los Arcos", hotelName: "Pensión Los Arcos", 
            coordinate: CLLocationCoordinate2D(latitude: 42.5715, longitude: -2.1918),
            dailyDistance: 21.3,
            cumulativeDistance: 134.3,
            elevationProfile: []),
        CaminoDestination(day: 8, date: Self.dateFormatter.date(from: "2024-05-08")!, locationName: "Logroño", hotelName: "Hotel Ciudad de Logroño", 
            coordinate: CLLocationCoordinate2D(latitude: 42.4660, longitude: -2.4450),
            dailyDistance: 28.6,
            cumulativeDistance: 162.9,
            elevationProfile: []),
        CaminoDestination(day: 9, date: Self.dateFormatter.date(from: "2024-05-09")!, locationName: "Nájera", hotelName: "Hotel Duques de Nájera", 
            coordinate: CLLocationCoordinate2D(latitude: 42.4160, longitude: -2.7290),
            dailyDistance: 29.6,
            cumulativeDistance: 192.5,
            elevationProfile: []),
        CaminoDestination(day: 10, date: Self.dateFormatter.date(from: "2024-05-10")!, locationName: "Santo Domingo de la Calzada", hotelName: "El Molino de Floren", 
            coordinate: CLLocationCoordinate2D(latitude: 42.4400, longitude: -2.9530),
            dailyDistance: 21.0,
            cumulativeDistance: 213.5,
            elevationProfile: []),
        CaminoDestination(day: 11, date: Self.dateFormatter.date(from: "2024-05-11")!, locationName: "Belorado", hotelName: "Hostel Punto B", 
            coordinate: CLLocationCoordinate2D(latitude: 42.4200, longitude: -3.1910),
            dailyDistance: 22.4,
            cumulativeDistance: 235.9,
            elevationProfile: []),
        CaminoDestination(day: 12, date: Self.dateFormatter.date(from: "2024-05-12")!, locationName: "San Juan de Ortega", hotelName: "Hotel Rural la Iglesia", 
            coordinate: CLLocationCoordinate2D(latitude: 42.3760, longitude: -3.4370),
            dailyDistance: 24.2,
            cumulativeDistance: 260.1,
            elevationProfile: []),
        CaminoDestination(day: 13, date: Self.dateFormatter.date(from: "2024-05-13")!, locationName: "Burgos", hotelName: "Hotel Cordón", 
            coordinate: CLLocationCoordinate2D(latitude: 42.3410, longitude: -3.7010),
            dailyDistance: 25.8,
            cumulativeDistance: 285.9,
            elevationProfile: []),
        CaminoDestination(day: 14, date: Self.dateFormatter.date(from: "2024-05-14")!, locationName: "Hornillos del Camino", hotelName: "De Sol A Sol", 
            coordinate: CLLocationCoordinate2D(latitude: 42.3130, longitude: -4.0460),
            dailyDistance: 20.8,
            cumulativeDistance: 306.7,
            elevationProfile: []),
        CaminoDestination(day: 15, date: Self.dateFormatter.date(from: "2024-05-15")!, locationName: "Castrojeriz", hotelName: "A Cien Leguas", 
            coordinate: CLLocationCoordinate2D(latitude: 42.2900, longitude: -4.1380),
            dailyDistance: 20.0,
            cumulativeDistance: 326.7,
            elevationProfile: []),
        CaminoDestination(day: 16, date: Self.dateFormatter.date(from: "2024-05-16")!, locationName: "Frómista", hotelName: "Eco Hotel Doña Mayor", 
            coordinate: CLLocationCoordinate2D(latitude: 42.2670, longitude: -4.4060),
            dailyDistance: 25.0,
            cumulativeDistance: 351.7,
            elevationProfile: []),
        CaminoDestination(day: 17, date: Self.dateFormatter.date(from: "2024-05-17")!, locationName: "Carrión de los Condes", hotelName: "Hostal La Corte", 
            coordinate: CLLocationCoordinate2D(latitude: 42.3380, longitude: -4.6030),
            dailyDistance: 19.2,
            cumulativeDistance: 370.9,
            elevationProfile: []),
        CaminoDestination(day: 18, date: Self.dateFormatter.date(from: "2024-05-18")!, locationName: "Calzadilla de la Cueza", hotelName: "Hostal Camino Real", 
            coordinate: CLLocationCoordinate2D(latitude: 42.3630, longitude: -4.8860),
            dailyDistance: 17.1,
            cumulativeDistance: 388.0,
            elevationProfile: []),
        CaminoDestination(day: 19, date: Self.dateFormatter.date(from: "2024-05-19")!, locationName: "Sahagún", hotelName: "Hostal Domus Viatoris", 
            coordinate: CLLocationCoordinate2D(latitude: 42.3710, longitude: -5.0290),
            dailyDistance: 22.2,
            cumulativeDistance: 410.2,
            elevationProfile: []),
        CaminoDestination(day: 20, date: Self.dateFormatter.date(from: "2024-05-20")!, locationName: "El Burgo Ranero", hotelName: "Hotel Castillo El Burgo", 
            coordinate: CLLocationCoordinate2D(latitude: 42.4220, longitude: -5.2200),
            dailyDistance: 17.7,
            cumulativeDistance: 427.9,
            elevationProfile: []),
        CaminoDestination(day: 21, date: Self.dateFormatter.date(from: "2024-05-21")!, locationName: "Mansilla de las Mulas", hotelName: "Alberguería del Camino", 
            coordinate: CLLocationCoordinate2D(latitude: 42.4990, longitude: -5.4170),
            dailyDistance: 18.6,
            cumulativeDistance: 446.5,
            elevationProfile: []),
        CaminoDestination(day: 22, date: Self.dateFormatter.date(from: "2024-05-22")!, locationName: "León", hotelName: "Hotel Alda Vía León", 
            coordinate: CLLocationCoordinate2D(latitude: 42.5990, longitude: -5.5710),
            dailyDistance: 18.5,
            cumulativeDistance: 465.0,
            elevationProfile: []),
        CaminoDestination(day: 23, date: Self.dateFormatter.date(from: "2024-05-23")!, locationName: "Villadangos del Páramo", hotelName: "TBD", 
            coordinate: CLLocationCoordinate2D(latitude: 42.5160, longitude: -5.7660),
            dailyDistance: 20.7,
            cumulativeDistance: 485.7,
            elevationProfile: []),
        CaminoDestination(day: 24, date: Self.dateFormatter.date(from: "2024-05-24")!, locationName: "Chozas de Abajo", hotelName: "Albergue San Antonio", 
            coordinate: CLLocationCoordinate2D(latitude: 42.5060, longitude: -5.6830),
            dailyDistance: 26.3,
            cumulativeDistance: 512.0,
            elevationProfile: []),
        CaminoDestination(day: 25, date: Self.dateFormatter.date(from: "2024-05-25")!, locationName: "Astorga", hotelName: "Hotel Astur Plaza", 
            coordinate: CLLocationCoordinate2D(latitude: 42.4570, longitude: -6.0560),
            dailyDistance: 20.5,
            cumulativeDistance: 532.5,
            elevationProfile: []),
        CaminoDestination(day: 26, date: Self.dateFormatter.date(from: "2024-05-26")!, locationName: "Rabanal del Camino", hotelName: "Hotel Rural Casa Indie", 
            coordinate: CLLocationCoordinate2D(latitude: 42.4810, longitude: -6.2840),
            dailyDistance: 20.5,
            cumulativeDistance: 553.0,
            elevationProfile: []),
        CaminoDestination(day: 27, date: Self.dateFormatter.date(from: "2024-05-27")!, locationName: "Ponferrada", hotelName: "Hotel El Castillo", 
            coordinate: CLLocationCoordinate2D(latitude: 42.5460, longitude: -6.5960),
            dailyDistance: 32.5,
            cumulativeDistance: 585.5,
            elevationProfile: []),
        CaminoDestination(day: 28, date: Self.dateFormatter.date(from: "2024-05-28")!, locationName: "Villafranca del Bierzo", hotelName: "Hostal Tres Campanas", 
            coordinate: CLLocationCoordinate2D(latitude: 42.6060, longitude: -6.8110),
            dailyDistance: 24.2,
            cumulativeDistance: 609.7,
            elevationProfile: []),
        CaminoDestination(day: 29, date: Self.dateFormatter.date(from: "2024-05-29")!, locationName: "O Cebreiro", hotelName: "Casa Navarro", 
            coordinate: CLLocationCoordinate2D(latitude: 42.7080, longitude: -7.0420),
            dailyDistance: 28.0,
            cumulativeDistance: 637.7,
            elevationProfile: []),
        CaminoDestination(day: 30, date: Self.dateFormatter.date(from: "2024-05-30")!, locationName: "Triacastela", hotelName: "Complexo Xacobeo", 
            coordinate: CLLocationCoordinate2D(latitude: 42.7550, longitude: -7.2370),
            dailyDistance: 20.8,
            cumulativeDistance: 658.5,
            elevationProfile: []),
        CaminoDestination(day: 31, date: Self.dateFormatter.date(from: "2024-05-31")!, locationName: "Sarria", hotelName: "Hotel Alfonso IX", 
            coordinate: CLLocationCoordinate2D(latitude: 42.7810, longitude: -7.4140),
            dailyDistance: 25.4,
            cumulativeDistance: 683.9,
            elevationProfile: []),
        CaminoDestination(day: 32, date: Self.dateFormatter.date(from: "2024-06-01")!, locationName: "Portomarín", hotelName: "Hotel Pousada de Portomarín", 
            coordinate: CLLocationCoordinate2D(latitude: 42.8080, longitude: -7.6160),
            dailyDistance: 22.4,
            cumulativeDistance: 706.3,
            elevationProfile: []),
        CaminoDestination(day: 33, date: Self.dateFormatter.date(from: "2024-06-02")!, locationName: "Palas de Rei", hotelName: "Hotel Casa Benilde", 
            coordinate: CLLocationCoordinate2D(latitude: 42.8740, longitude: -7.8680),
            dailyDistance: 24.8,
            cumulativeDistance: 731.1,
            elevationProfile: []),
        CaminoDestination(day: 34, date: Self.dateFormatter.date(from: "2024-06-03")!, locationName: "Arzúa", hotelName: "Hotel Arzúa", 
            coordinate: CLLocationCoordinate2D(latitude: 42.9280, longitude: -8.1930),
            dailyDistance: 28.5,
            cumulativeDistance: 759.6,
            elevationProfile: []),
        CaminoDestination(day: 35, date: Self.dateFormatter.date(from: "2024-06-04")!, locationName: "O Pedrouzo", hotelName: "Hotel O Acivro", 
            coordinate: CLLocationCoordinate2D(latitude: 42.9090, longitude: -8.4320),
            dailyDistance: 19.3,
            cumulativeDistance: 778.9,
            elevationProfile: []),
        CaminoDestination(day: 36, date: Self.dateFormatter.date(from: "2024-06-05")!, locationName: "Santiago de Compostela", hotelName: "Hotel Compostela", 
            coordinate: CLLocationCoordinate2D(latitude: 42.8800, longitude: -8.5450),
            dailyDistance: 20.2,
            cumulativeDistance: 799.1,
            elevationProfile: [])
    ]
    
    public init(day: Int, date: Date, locationName: String, hotelName: String, coordinate: CLLocationCoordinate2D, dailyDistance: Double, cumulativeDistance: Double, elevationProfile: [(distance: Double, elevation: Double)] = []) {
        self.day = day
        self.date = date
        self.locationName = locationName
        self.hotelName = hotelName
        self.coordinate = coordinate
        self.dailyDistance = dailyDistance
        self.cumulativeDistance = cumulativeDistance
        self.elevationProfile = elevationProfile
    }
} 